import type { SearchResponse, StationResponse, StatsResponse, TrainResponse } from "./types";

const today = new Date().toISOString().slice(0, 10);

const isoAt = (hour: number, minute: number) => {
  const date = new Date();
  date.setHours(hour, minute, 0, 0);
  return date.toISOString();
};

const isoOffsetMinutes = (offsetMinutes: number) => {
  const date = new Date(Date.now() + offsetMinutes * 60 * 1000);
  date.setSeconds(0, 0);
  return date.toISOString();
};

export const demoSearch: SearchResponse = {
  query: "Warszawa Centralna",
  date: today,
  demo: true,
  warnings: [],
  stations: [
    { id: 33605, name: "Warszawa Centralna" },
    { id: 5100071, name: "Warszawa Zachodnia" },
    { id: 5100067, name: "Warszawa Wschodnia" },
  ],
  trains: [
    {
      scheduleId: 25,
      orderId: 6104,
      operationOrderId: 6104,
      trainOrderId: 0,
      operatingDate: today,
      label: "IC 6104 Sienkiewicz",
      name: "Sienkiewicz",
      number: "6104",
      category: "IC",
      carrierCode: "PKPIC",
      carrierName: "PKP Intercity",
      origin: "Wroclaw Glowny",
      destination: "Warszawa Wschodnia",
      stationCount: 13,
      firstDeparture: isoAt(7, 14),
      lastArrival: isoAt(12, 3),
    },
  ],
};

export const demoStation: StationResponse = {
  station: { id: 33605, name: "Warszawa Centralna" },
  date: today,
  demo: true,
  generatedAt: new Date().toISOString(),
  board: [
    {
      id: "demo-ic-6104-dep",
      kind: "departure",
      stationId: 33605,
      scheduleId: 25,
      orderId: 6104,
      operationOrderId: 6104,
      operatingDate: today,
      label: "IC 6104 Sienkiewicz",
      name: "Sienkiewicz",
      number: "6104",
      category: "IC",
      carrierCode: "PKPIC",
      carrierName: "PKP Intercity",
      origin: "Wroclaw Glowny",
      destination: "Warszawa Wschodnia",
      firstDeparture: isoAt(7, 14),
      lastArrival: isoAt(12, 3),
      plannedTime: isoOffsetMinutes(-48),
      actualTime: isoOffsetMinutes(-40),
      delayMinutes: 8,
      delayLabel: "+8 min",
      platform: "4",
      track: "8",
      stopTypeName: "postoj handlowy",
      status: { code: "P", label: "W trasie", tone: "live" },
      isConfirmed: true,
      isCancelled: false,
    },
    {
      id: "demo-eic-3502-arr",
      kind: "arrival",
      stationId: 33605,
      scheduleId: 25,
      orderId: 3502,
      operationOrderId: 3502,
      operatingDate: today,
      label: "EIC 3502 Tatry",
      name: "Tatry",
      number: "3502",
      category: "EIC",
      carrierCode: "PKPIC",
      carrierName: "PKP Intercity",
      origin: "Krakow Glowny",
      destination: "Gdynia Glowna",
      firstDeparture: isoAt(9, 2),
      lastArrival: isoAt(15, 48),
      plannedTime: isoOffsetMinutes(12),
      actualTime: null,
      delayMinutes: 0,
      delayLabel: "Planowo",
      platform: "2",
      track: "6",
      stopTypeName: "postoj handlowy",
      status: { code: "S", label: "Nie rozpoczal", tone: "idle" },
      isConfirmed: false,
      isCancelled: false,
    },
    {
      id: "demo-r-19316-dep",
      kind: "departure",
      stationId: 33605,
      scheduleId: 25,
      orderId: 19316,
      operationOrderId: 19316,
      operatingDate: today,
      label: "R 19316",
      name: null,
      number: "19316",
      category: "R",
      carrierCode: "KM",
      carrierName: "Koleje Mazowieckie",
      origin: "Warszawa Zachodnia",
      destination: "Radom Glowny",
      firstDeparture: isoAt(14, 5),
      lastArrival: isoAt(16, 18),
      plannedTime: isoOffsetMinutes(-12),
      actualTime: isoOffsetMinutes(-12),
      delayMinutes: 0,
      delayLabel: "Planowo",
      platform: "1",
      track: "2",
      stopTypeName: "postoj handlowy",
      status: { code: "P", label: "W trasie", tone: "live" },
      isConfirmed: true,
      isCancelled: false,
    },
  ],
  disruptions: [
    {
      id: "demo-u1",
      type: "Prace torowe",
      message: "Mozliwe zmiany peronow na odcinku Warszawa Zachodnia - Warszawa Centralna.",
      startStation: "Warszawa Zachodnia",
      endStation: "Warszawa Centralna",
      affectedRoutesCount: 18,
    },
  ],
};

export const demoTrain: TrainResponse = {
  train: demoSearch.trains[0],
  operationOrderId: 6104,
  date: today,
  demo: true,
  generatedAt: new Date().toISOString(),
  status: { code: "P", label: "W trasie", tone: "live" },
  timeline: [
    {
      stationId: 1,
      stationName: "Wroclaw Glowny",
      orderNumber: 1,
      plannedArrival: null,
      plannedDeparture: isoAt(7, 14),
      actualArrival: null,
      actualDeparture: isoAt(7, 14),
      arrivalDelayMinutes: null,
      departureDelayMinutes: 0,
      platform: "3",
      track: "5",
      isConfirmed: true,
      isCancelled: false,
      stopTypeName: "postoj handlowy",
    },
    {
      stationId: 2,
      stationName: "Opole Glowne",
      orderNumber: 2,
      plannedArrival: isoAt(8, 11),
      plannedDeparture: isoAt(8, 14),
      actualArrival: isoAt(8, 18),
      actualDeparture: isoAt(8, 21),
      arrivalDelayMinutes: 7,
      departureDelayMinutes: 7,
      platform: "2",
      track: "4",
      isConfirmed: true,
      isCancelled: false,
      stopTypeName: "postoj handlowy",
    },
    {
      stationId: 3,
      stationName: "Warszawa Centralna",
      orderNumber: 12,
      plannedArrival: isoAt(12, 8),
      plannedDeparture: isoAt(12, 11),
      actualArrival: isoAt(12, 16),
      actualDeparture: isoAt(12, 19),
      arrivalDelayMinutes: 8,
      departureDelayMinutes: 8,
      platform: "4",
      track: "8",
      isConfirmed: true,
      isCancelled: false,
      stopTypeName: "postoj handlowy",
    },
    {
      stationId: 4,
      stationName: "Warszawa Wschodnia",
      orderNumber: 13,
      plannedArrival: isoAt(12, 23),
      plannedDeparture: null,
      actualArrival: null,
      actualDeparture: null,
      arrivalDelayMinutes: 8,
      departureDelayMinutes: null,
      platform: "6",
      track: "10",
      isConfirmed: false,
      isCancelled: false,
      stopTypeName: "koniec trasy",
    },
  ],
};

export const demoStats: StatsResponse = {
  date: today,
  demo: true,
  generatedAt: new Date().toISOString(),
  stats: {
    totalTrains: 4860,
    notStarted: 1420,
    inProgress: 1118,
    completed: 2298,
    cancelled: 18,
    partialCancelled: 6,
  },
};
